# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'interfaceStack.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QSize(800, 600))
        MainWindow.setMaximumSize(QSize(800, 600))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(51, 51, 51, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(76, 76, 76, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(63, 63, 63, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(25, 25, 25, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(34, 34, 34, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush6 = QBrush(QColor(68, 68, 68, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush7 = QBrush(QColor(0, 0, 0, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        brush8 = QBrush(QColor(64, 120, 192, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Highlight, brush8)
        palette.setBrush(QPalette.Active, QPalette.Link, brush8)
        brush9 = QBrush(QColor(110, 84, 148, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        brush10 = QBrush(QColor(222, 221, 218, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush10)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
        brush11 = QBrush(QColor(255, 255, 255, 128))
        brush11.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush11)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush8)
        palette.setBrush(QPalette.Inactive, QPalette.Link, brush8)
        palette.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush10)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush11)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        brush12 = QBrush(QColor(145, 145, 145, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Highlight, brush12)
        palette.setBrush(QPalette.Disabled, QPalette.Link, brush8)
        palette.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush10)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush11)
#endif
        MainWindow.setPalette(palette)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 801, 581))
        self.main = QWidget()
        self.main.setObjectName(u"main")
        self.buttonGithub = QPushButton(self.main)
        self.buttonGithub.setObjectName(u"buttonGithub")
        self.buttonGithub.setGeometry(QRect(10, 480, 91, 91))
        font = QFont()
        font.setPointSize(18)
        self.buttonGithub.setFont(font)
        self.buttonGithub.setStyleSheet(u"QPushButton {\n"
"\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"\n"
"padding: 10px;\n"
"\n"
"border: none;\n"
"\n"
"\n"
"\n"
"border-radius: 45%;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"	background-color: rgb(85,85,85);\n"
"}")
        icon = QIcon()
        icon.addFile(u"assets/images/25231.png", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonGithub.setIcon(icon)
        self.buttonGithub.setIconSize(QSize(58, 58))
        self.mainTitle = QLabel(self.main)
        self.mainTitle.setObjectName(u"mainTitle")
        self.mainTitle.setGeometry(QRect(210, 60, 341, 71))
        font1 = QFont()
        font1.setFamily(u"Good Timing")
        font1.setPointSize(48)
        font1.setBold(True)
        font1.setItalic(False)
        font1.setWeight(75)
        self.mainTitle.setFont(font1)
        self.mainTitle.setStyleSheet(u"color: #fff;")
        self.buttonAccessHide = QPushButton(self.main)
        self.buttonAccessHide.setObjectName(u"buttonAccessHide")
        self.buttonAccessHide.setGeometry(QRect(290, 280, 191, 41))
        self.buttonAccessHide.setFont(font)
        self.mainLabel = QLabel(self.main)
        self.mainLabel.setObjectName(u"mainLabel")
        self.mainLabel.setGeometry(QRect(90, 190, 601, 41))
        font2 = QFont()
        font2.setPointSize(24)
        self.mainLabel.setFont(font2)
        self.buttonAccessShow = QPushButton(self.main)
        self.buttonAccessShow.setObjectName(u"buttonAccessShow")
        self.buttonAccessShow.setGeometry(QRect(290, 340, 191, 41))
        self.buttonAccessShow.setFont(font)
        self.stackedWidget.addWidget(self.main)
        self.hide1 = QWidget()
        self.hide1.setObjectName(u"hide1")
        self.imageDirectoryInputLabel = QLabel(self.hide1)
        self.imageDirectoryInputLabel.setObjectName(u"imageDirectoryInputLabel")
        self.imageDirectoryInputLabel.setGeometry(QRect(100, 180, 291, 20))
        font3 = QFont()
        font3.setPointSize(14)
        self.imageDirectoryInputLabel.setFont(font3)
        self.imageDirectoryInput = QLineEdit(self.hide1)
        self.imageDirectoryInput.setObjectName(u"imageDirectoryInput")
        self.imageDirectoryInput.setGeometry(QRect(100, 210, 441, 31))
        self.subpixelSelectorLabel = QLabel(self.hide1)
        self.subpixelSelectorLabel.setObjectName(u"subpixelSelectorLabel")
        self.subpixelSelectorLabel.setGeometry(QRect(100, 280, 351, 20))
        self.subpixelSelectorLabel.setFont(font3)
        self.buttonGoBackHide1 = QPushButton(self.hide1)
        self.buttonGoBackHide1.setObjectName(u"buttonGoBackHide1")
        self.buttonGoBackHide1.setGeometry(QRect(10, 510, 71, 31))
        self.subpixelSelectorComboBox = QComboBox(self.hide1)
        self.subpixelSelectorComboBox.addItem("")
        self.subpixelSelectorComboBox.addItem("")
        self.subpixelSelectorComboBox.addItem("")
        self.subpixelSelectorComboBox.addItem("")
        self.subpixelSelectorComboBox.setObjectName(u"subpixelSelectorComboBox")
        self.subpixelSelectorComboBox.setGeometry(QRect(100, 310, 571, 41))
        self.subpixelSelectorComboBox.setFont(font3)
        self.hide1Title = QLabel(self.hide1)
        self.hide1Title.setObjectName(u"hide1Title")
        self.hide1Title.setGeometry(QRect(220, 50, 331, 61))
        font4 = QFont()
        font4.setPointSize(36)
        self.hide1Title.setFont(font4)
        self.buttonBrowseFilesInput = QPushButton(self.hide1)
        self.buttonBrowseFilesInput.setObjectName(u"buttonBrowseFilesInput")
        self.buttonBrowseFilesInput.setGeometry(QRect(560, 210, 111, 31))
        self.buttonGoNextHide1 = QPushButton(self.hide1)
        self.buttonGoNextHide1.setObjectName(u"buttonGoNextHide1")
        self.buttonGoNextHide1.setGeometry(QRect(250, 380, 271, 41))
        font5 = QFont()
        font5.setPointSize(16)
        self.buttonGoNextHide1.setFont(font5)
        self.buttonGoNextHide1.setIconSize(QSize(24, 24))
        self.stackedWidget.addWidget(self.hide1)
        self.hide2 = QWidget()
        self.hide2.setObjectName(u"hide2")
        self.hide2Title = QLabel(self.hide2)
        self.hide2Title.setObjectName(u"hide2Title")
        self.hide2Title.setGeometry(QRect(220, 50, 331, 61))
        self.hide2Title.setFont(font4)
        self.messageInputLabel = QLabel(self.hide2)
        self.messageInputLabel.setObjectName(u"messageInputLabel")
        self.messageInputLabel.setGeometry(QRect(100, 180, 231, 20))
        self.messageInputLabel.setFont(font3)
        self.buttonSubmitHide2 = QPushButton(self.hide2)
        self.buttonSubmitHide2.setObjectName(u"buttonSubmitHide2")
        self.buttonSubmitHide2.setGeometry(QRect(250, 380, 271, 41))
        self.buttonSubmitHide2.setFont(font5)
        self.buttonGoBackHide2 = QPushButton(self.hide2)
        self.buttonGoBackHide2.setObjectName(u"buttonGoBackHide2")
        self.buttonGoBackHide2.setGeometry(QRect(10, 510, 71, 31))
        self.messageInput = QTextEdit(self.hide2)
        self.messageInput.setObjectName(u"messageInput")
        self.messageInput.setGeometry(QRect(100, 210, 571, 141))
        self.stackedWidget.addWidget(self.hide2)
        self.hide3 = QWidget()
        self.hide3.setObjectName(u"hide3")
        self.imageDirectoryOutput = QLineEdit(self.hide3)
        self.imageDirectoryOutput.setObjectName(u"imageDirectoryOutput")
        self.imageDirectoryOutput.setGeometry(QRect(100, 210, 441, 31))
        self.hide3Title = QLabel(self.hide3)
        self.hide3Title.setObjectName(u"hide3Title")
        self.hide3Title.setGeometry(QRect(220, 50, 331, 61))
        self.hide3Title.setFont(font4)
        self.hide3Title.setAlignment(Qt.AlignCenter)
        self.imageDirectoryOutputLabel = QLabel(self.hide3)
        self.imageDirectoryOutputLabel.setObjectName(u"imageDirectoryOutputLabel")
        self.imageDirectoryOutputLabel.setGeometry(QRect(100, 180, 261, 20))
        self.imageDirectoryOutputLabel.setFont(font3)
        self.buttonBrowseDirectoriesOutput = QPushButton(self.hide3)
        self.buttonBrowseDirectoriesOutput.setObjectName(u"buttonBrowseDirectoriesOutput")
        self.buttonBrowseDirectoriesOutput.setGeometry(QRect(560, 210, 111, 31))
        self.buttonDownloadImage = QPushButton(self.hide3)
        self.buttonDownloadImage.setObjectName(u"buttonDownloadImage")
        self.buttonDownloadImage.setGeometry(QRect(250, 380, 271, 41))
        self.buttonDownloadImage.setFont(font5)
        icon1 = QIcon()
        icon1.addFile(u"assets/images/img_70157.png", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonDownloadImage.setIcon(icon1)
        self.buttonDownloadImage.setIconSize(QSize(24, 24))
        self.buttonGoBackHide3 = QPushButton(self.hide3)
        self.buttonGoBackHide3.setObjectName(u"buttonGoBackHide3")
        self.buttonGoBackHide3.setGeometry(QRect(10, 510, 71, 31))
        self.imageNameOutput = QLineEdit(self.hide3)
        self.imageNameOutput.setObjectName(u"imageNameOutput")
        self.imageNameOutput.setGeometry(QRect(100, 310, 571, 31))
        self.imageNameOutputLabel = QLabel(self.hide3)
        self.imageNameOutputLabel.setObjectName(u"imageNameOutputLabel")
        self.imageNameOutputLabel.setGeometry(QRect(100, 280, 261, 20))
        self.imageNameOutputLabel.setFont(font3)
        self.stackedWidget.addWidget(self.hide3)
        self.show1 = QWidget()
        self.show1.setObjectName(u"show1")
        self.buttonBrowseFilesInput2 = QPushButton(self.show1)
        self.buttonBrowseFilesInput2.setObjectName(u"buttonBrowseFilesInput2")
        self.buttonBrowseFilesInput2.setGeometry(QRect(560, 210, 111, 31))
        self.subpixelSelectorComboBox2 = QComboBox(self.show1)
        self.subpixelSelectorComboBox2.addItem("")
        self.subpixelSelectorComboBox2.addItem("")
        self.subpixelSelectorComboBox2.addItem("")
        self.subpixelSelectorComboBox2.addItem("")
        self.subpixelSelectorComboBox2.setObjectName(u"subpixelSelectorComboBox2")
        self.subpixelSelectorComboBox2.setGeometry(QRect(100, 310, 571, 41))
        self.subpixelSelectorComboBox2.setFont(font3)
        self.show1Title = QLabel(self.show1)
        self.show1Title.setObjectName(u"show1Title")
        self.show1Title.setGeometry(QRect(220, 50, 331, 61))
        self.show1Title.setFont(font4)
        self.show1Title.setAlignment(Qt.AlignCenter)
        self.buttonGoBackShow1 = QPushButton(self.show1)
        self.buttonGoBackShow1.setObjectName(u"buttonGoBackShow1")
        self.buttonGoBackShow1.setGeometry(QRect(10, 510, 71, 31))
        self.imageDirectoryInputLabel2 = QLabel(self.show1)
        self.imageDirectoryInputLabel2.setObjectName(u"imageDirectoryInputLabel2")
        self.imageDirectoryInputLabel2.setGeometry(QRect(100, 180, 291, 20))
        self.imageDirectoryInputLabel2.setFont(font3)
        self.buttonSubmitShow1 = QPushButton(self.show1)
        self.buttonSubmitShow1.setObjectName(u"buttonSubmitShow1")
        self.buttonSubmitShow1.setGeometry(QRect(250, 380, 271, 41))
        self.buttonSubmitShow1.setFont(font5)
        self.imageDirectoryInput2 = QLineEdit(self.show1)
        self.imageDirectoryInput2.setObjectName(u"imageDirectoryInput2")
        self.imageDirectoryInput2.setGeometry(QRect(100, 210, 441, 31))
        self.subpixelSelectorLabel2 = QLabel(self.show1)
        self.subpixelSelectorLabel2.setObjectName(u"subpixelSelectorLabel2")
        self.subpixelSelectorLabel2.setGeometry(QRect(100, 280, 351, 20))
        self.subpixelSelectorLabel2.setFont(font3)
        self.stackedWidget.addWidget(self.show1)
        self.show2 = QWidget()
        self.show2.setObjectName(u"show2")
        self.buttonBrowseDirectoriesOutput2 = QPushButton(self.show2)
        self.buttonBrowseDirectoriesOutput2.setObjectName(u"buttonBrowseDirectoriesOutput2")
        self.buttonBrowseDirectoriesOutput2.setGeometry(QRect(560, 210, 111, 31))
        self.show2Title = QLabel(self.show2)
        self.show2Title.setObjectName(u"show2Title")
        self.show2Title.setGeometry(QRect(220, 50, 331, 61))
        self.show2Title.setFont(font4)
        self.show2Title.setAlignment(Qt.AlignCenter)
        self.imageDirectoryOutput2 = QLineEdit(self.show2)
        self.imageDirectoryOutput2.setObjectName(u"imageDirectoryOutput2")
        self.imageDirectoryOutput2.setGeometry(QRect(100, 210, 441, 31))
        self.buttonGoBackShow2 = QPushButton(self.show2)
        self.buttonGoBackShow2.setObjectName(u"buttonGoBackShow2")
        self.buttonGoBackShow2.setGeometry(QRect(10, 510, 71, 31))
        self.imageDirectoryOutputLabel2 = QLabel(self.show2)
        self.imageDirectoryOutputLabel2.setObjectName(u"imageDirectoryOutputLabel2")
        self.imageDirectoryOutputLabel2.setGeometry(QRect(100, 180, 261, 20))
        self.imageDirectoryOutputLabel2.setFont(font3)
        self.buttonDownloadImage2 = QPushButton(self.show2)
        self.buttonDownloadImage2.setObjectName(u"buttonDownloadImage2")
        self.buttonDownloadImage2.setGeometry(QRect(250, 380, 271, 41))
        self.buttonDownloadImage2.setFont(font5)
        self.buttonDownloadImage2.setIcon(icon1)
        self.buttonDownloadImage2.setIconSize(QSize(24, 24))
        self.textNameOutputLabel = QLabel(self.show2)
        self.textNameOutputLabel.setObjectName(u"textNameOutputLabel")
        self.textNameOutputLabel.setGeometry(QRect(100, 280, 261, 20))
        self.textNameOutputLabel.setFont(font3)
        self.textNameOutput = QLineEdit(self.show2)
        self.textNameOutput.setObjectName(u"textNameOutput")
        self.textNameOutput.setGeometry(QRect(100, 310, 571, 31))
        self.stackedWidget.addWidget(self.show2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(5)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"OpenSteg", None))
        self.buttonGithub.setText("")
        self.mainTitle.setText(QCoreApplication.translate("MainWindow", u"OpenSteg", None))
        self.buttonAccessHide.setText(QCoreApplication.translate("MainWindow", u"Esteganografia", None))
        self.mainLabel.setText(QCoreApplication.translate("MainWindow", u"Por favor, selecione a opera\u00e7\u00e3o desejada.", None))
        self.buttonAccessShow.setText(QCoreApplication.translate("MainWindow", u"Estegan\u00e1lise", None))
        self.imageDirectoryInputLabel.setText(QCoreApplication.translate("MainWindow", u"Diret\u00f3rio da imagem de entrada:", None))
        self.subpixelSelectorLabel.setText(QCoreApplication.translate("MainWindow", u"Selecione os subpixels a serem editados:", None))
        self.buttonGoBackHide1.setText(QCoreApplication.translate("MainWindow", u"Voltar", None))
        self.subpixelSelectorComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"RGB", None))
        self.subpixelSelectorComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"R", None))
        self.subpixelSelectorComboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"G", None))
        self.subpixelSelectorComboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"B", None))

        self.hide1Title.setText(QCoreApplication.translate("MainWindow", u"Esteganografia", None))
        self.buttonBrowseFilesInput.setText(QCoreApplication.translate("MainWindow", u"Buscar", None))
        self.buttonGoNextHide1.setText(QCoreApplication.translate("MainWindow", u"Pr\u00f3ximo", None))
        self.hide2Title.setText(QCoreApplication.translate("MainWindow", u"Esteganografia", None))
        self.messageInputLabel.setText(QCoreApplication.translate("MainWindow", u"Mensagem a ser ocultada:", None))
        self.buttonSubmitHide2.setText(QCoreApplication.translate("MainWindow", u"Submeter", None))
        self.buttonGoBackHide2.setText(QCoreApplication.translate("MainWindow", u"Voltar", None))
        self.hide3Title.setText(QCoreApplication.translate("MainWindow", u"Esteganografia", None))
        self.imageDirectoryOutputLabel.setText(QCoreApplication.translate("MainWindow", u"Diret\u00f3rio da imagem de sa\u00edda:", None))
        self.buttonBrowseDirectoriesOutput.setText(QCoreApplication.translate("MainWindow", u"Buscar", None))
        self.buttonDownloadImage.setText(QCoreApplication.translate("MainWindow", u" Download", None))
        self.buttonGoBackHide3.setText(QCoreApplication.translate("MainWindow", u"Voltar", None))
        self.imageNameOutputLabel.setText(QCoreApplication.translate("MainWindow", u"Nome da imagem:", None))
        self.buttonBrowseFilesInput2.setText(QCoreApplication.translate("MainWindow", u"Buscar", None))
        self.subpixelSelectorComboBox2.setItemText(0, QCoreApplication.translate("MainWindow", u"RGB", None))
        self.subpixelSelectorComboBox2.setItemText(1, QCoreApplication.translate("MainWindow", u"R", None))
        self.subpixelSelectorComboBox2.setItemText(2, QCoreApplication.translate("MainWindow", u"G", None))
        self.subpixelSelectorComboBox2.setItemText(3, QCoreApplication.translate("MainWindow", u"B", None))

        self.show1Title.setText(QCoreApplication.translate("MainWindow", u"Estegan\u00e1lise", None))
        self.buttonGoBackShow1.setText(QCoreApplication.translate("MainWindow", u"Voltar", None))
        self.imageDirectoryInputLabel2.setText(QCoreApplication.translate("MainWindow", u"Diret\u00f3rio da imagem de entrada:", None))
        self.buttonSubmitShow1.setText(QCoreApplication.translate("MainWindow", u"Submeter", None))
        self.subpixelSelectorLabel2.setText(QCoreApplication.translate("MainWindow", u"Selecione os subpixels a serem verificados:", None))
        self.buttonBrowseDirectoriesOutput2.setText(QCoreApplication.translate("MainWindow", u"Buscar", None))
        self.show2Title.setText(QCoreApplication.translate("MainWindow", u"Estegan\u00e1lise", None))
        self.buttonGoBackShow2.setText(QCoreApplication.translate("MainWindow", u"Voltar", None))
        self.imageDirectoryOutputLabel2.setText(QCoreApplication.translate("MainWindow", u"Diret\u00f3rio do texto de sa\u00edda:", None))
        self.buttonDownloadImage2.setText(QCoreApplication.translate("MainWindow", u" Download", None))
        self.textNameOutputLabel.setText(QCoreApplication.translate("MainWindow", u"Nome do arquivo de texto:", None))
    # retranslateUi

